# Ref: https://docs.docker.com/compose/compose-file/
version: '3'

services:

###############################
# Setup Node Server Container #
###############################

  server: 
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
      - ./server/src:/usr/src/app/server/src
    command: yarn start

####################################
# Setup React Web Server Container #
####################################

  client: 
    build: ./client
    expose:
      - ${APP_SERVER_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
      - ./client/src:/usr/src/app/client/src
      - ./client/public:/usr/src/app/client/public
    links:
      - server
    command: yarn start