apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31156
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: api
  sessionAffinity: None
  type: LoadBalancer
