apiVersion: v1
kind: Service
metadata:
  generateName: mongo-0-
  labels:
    run: mongo-service
  name: mongo-service
  namespace: default
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongo-service
  sessionAffinity: None
  type: ClusterIP
