# Configuration for the StatefulSet and specific pod specs
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: "mongo"
 replicas: 1
 selector:  
    matchLabels:  # has to match .spec.template.metadata.labels
       role: mongo
       run: mongo-service
 template:
   metadata:
     labels:
       role: mongo
       run: mongo-service
   # Pod Spec
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo
         command: ["/bin/sh","-c"]
         args: 
           - mongod --replSet rs0 --bind_ip_all
           - mongo
           - rs.initiate()
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
 # Storage Volumne Configuration for each pod
 volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
     annotations:
       volume.beta.kubernetes.io/storage-class: "fast"
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 10Gi