apiVersion: v1
kind: Service
metadata:
  generateName: mongo-0-
  labels:
    controller-revision-hash: mongo-64bb499fcd
    environment: test
    role: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  name: mongo-0-wrpjr
  namespace: default
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    controller-revision-hash: mongo-64bb499fcd
    environment: test
    role: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  sessionAffinity: None
  type: ClusterIP
